version: "3.7"
services: 
    web:
        build: .
        volumes: 
            - ./site:/var/www/html
        ports: 
            - 80:80
    db:  
        image: mysql    
        volumes: 
            - ./data:/var/lib/mysql
        environment:     
            MYSQL_ROOT_PASSWORD: 12345
            MYSQL_DATABASE: battleships    
        ports: 
            - 3306:3306